### ISSUE TITLE
Vbscript / Zipfile is detected as malicious by the virus scanner. 

### ISSUE THREAD

**Issue by igitwat** [GHbasicuser/RB2RS-Database-Updater#1]
I use your script since the beginning of november, thank you. But:
Since mid-November I can not run, nor download the vb-script. Bitdefender detects a Trojan.GenericKD.637338116.
A check with Virustotal.om also reports a Trojan with Kaspersky and eScan, among others. 
I sent a message to Bitdefender, a week ago. So far no change made (72h response time).

![Screenshot 2022-12-07 Virustotal](https://user-images.githubusercontent.com/16595367/206228588-0f42226d-114b-476a-a6e1-a4f8a463b981.png)

**Comment by GHbasicuser** [comment]
Hi Igitwat

Thank you for this information and your message sent to Bitdefender. 

I have also just reported this false positive to Bitdefender and Kasperky. I hope that at least one technician will take the time to analyse the script and correct this error. 🤔

Hoping that this will be resolved soon 🙄, I can only suggest that you exclude this file (at least the .vbs file) from the scan performed by your antivirus. 

Another possibility is to use the redirection method (via the windows hosts file) 😐 : https://www.radiosure.fr

King regards,
Philippe

**Comment by JazzfanRS** [comment]
I used the script today with no issues. I do recall there was warnings from Windows 10 for a script or .bat file located on the DB server, but that was in early days of development before you created this script.

**Comment by GHbasicuser** [comment]
Hello

I received an answer from one of the Malware Analysts at Kaspersky : 

>Hello,
>
>Sorry, it was a false detection. It will be fixed.
>Thank you for your help."
>
>(....)

🙂👍

Philippe

**Comment by igitwat** [comment]
Thanks, tested today, problem solved.

**Comment by GHbasicuser** [comment]
Yes, now according to the virustotal site it is almost back to "normal". 🙂

![](https://zupimages.net/up/22/49/3899.jpg)
