### ISSUE TITLE
Error in one PC

### ISSUE THREAD

**Issue by yardstudio** [GHbasicuser/RB2RS-Database-Updater#2]
![2022-12-11_14-19-32](https://user-images.githubusercontent.com/25852179/206906085-999d7d08-c95e-4d05-95a2-0de0123b71dc.png)

**Comment by GHbasicuser** [comment]
Hi

It seems that a character has been added at the very beginning of line 9 🤔 :

`Minimum_waiting_time_to_redownload = 12 'duration in hours'`

I get the same error message by adding a character like this one ";"  at the beginning of the line :

`;Minimum_waiting_time_to_redownload = 12 'duration in hours'`

It might be best to re-download the VBS file from this repository. 😐

Regards,
Philippe

**Comment by yardstudio** [comment]
I downloaded raw and all is OK now thx
![2022-12-11_16-58-05](https://user-images.githubusercontent.com/25852179/206914198-ee841e9d-14e0-4fcb-ad89-e591fbd8a26b.png)
