### ISSUE TITLE
Script works despite minor error and how I fixed it.

### ISSUE THREAD

**Issue by JazzfanRS** [GHbasicuser/RB2RS-Database-Updater#4]
Been using the script for months despite this error message, because the database is still updated. 
![Screenshot 2023-11-01 113023](https://github.com/GHbasicuser/RB2RS-Database-Updater/assets/103217961/031a50c0-4dc4-4895-bf63-a8353d6b17ea)
I commented out line 100 and now Update successful pop-up appears.
![Screenshot 2023-11-01 114109](https://github.com/GHbasicuser/RB2RS-Database-Updater/assets/103217961/e14febe6-fefe-4b46-82eb-eb58b444f08a)

**Comment by GHbasicuser** [comment]
Hello !

It's a bit surprising that this happened.. the RadioSure.xml file may have been missing, deleted or write-blocked (e.g. opened by a text editor). 🤔

The "script" assumes that this file is present, because RadioSure generates it and it seems that it is present from the first installation.

Have you recently reinstalled RS ? Was the ".xml" file present and available ?

I think that you can uncomment this line now.. unless the .xml file is again absent or "blocked" it should work as before. 🤞

However.. maybe I'll add a test to avoid this. 😐 (it must be a rare occurrence.. at least I think so.)

Thanks for your feedback,

Philippe

**Comment by JazzfanRS** [comment]
Hello! Yes, I did in fact reinstall RadioSure. But I think I had this issue before. I recently reinstalled Windows 10 Home. Upon reinstall I chose to have all personal files and 3rd party software on a separate hard drive and installed RS into a Program(x86) folder rather than APPDATA. I doubt this has any bearing. It was really a minor bug and forgot to notify anyone until now since I don’t know how to write scripts. I just experimented to see if I could stop the behavior. 

All has been quiet on Reddit. I try to post every other month ‘just because’. Only recently noticed the website showing a playable stations list. I haven’t mentioned it as yet. Maybe this month. 

Cheers. Jerry

**Comment by GHbasicuser** [comment]
I can see (for the moment) only 2 possible explanations for this error message 🤔 :
- the RadioSure.xml file is (or was) missing (hidden attribute ?).
- the script can't find the **LastStationsUpdateCheck** tag in the RadioSure.xml file. (corrupted/modified file ?)

If it's one, or the other, of these possibilities, I can solve it very easily (by skipping the xml file modification), but the Radiosure.xml file is supposed to be there and so is the tag. 😮

If the RadioSure.xml file is present in your RadioSure folder, can you restore the script to its original state, delete the latest.zip file (in Station folder), and then run the script again ? 😐 Do you still have an error ? 

The radio player on the site has been removed 😅, it was an addition by François (for his personal use mainly), a script based on "That Radio Player"... but the weight of the file (linked to the size of the base,  not very suitable for this radio player), the rudimentary interface, ... and the fact that the site is dedicated to the use of RadioSure made me suggest not to put this tool too much forward. 😓

**Comment by GHbasicuser** [comment]
I've just noticed that when installing RadioSure with the official installer, the xml file is not present until RadioSure is started. As a result, the error may occur if the script is run before the very first use of RadioSure. 😑

I'll add a test for the presence of the file and the presence of the tag in a future version. Thanx. 😉

**Comment by JazzfanRS** [comment]
I don't surf stations much, if at all anymore, so I only ever update every other month or so. Glad to have brought this to your attention. I am not sure the exact way in which this happened. But again, it still updated with this error present. It apparently did everything up to line 100 and then stopped. I will be notified when you update the repo.

Your welcome.

**Comment by GHbasicuser** [comment]
>But again, it still updated with this error present. It apparently did everything up to line 100 and then stopped.

The problem on line 100 can be explained by the absence of the RadioSure.xml file (or the absence of the "LastStationsUpdateCheck " tag inside). 

- Do you have the RadioSure.xml file in your RadioSure folder ? 😐
- Do you have this problem every 2 months ? Or every time you use it ?
- Does your version of RS (2.2.1046 ??) use a configuration source other than the RadioSure.xml file? (the registry ??) 🤔

Thank you for any additional information. 🙂

Edit: this [new version](https://github.com/GHbasicuser/RB2RS-Database-Updater/blob/main/db-update.vbs) checks for the presence of the XML file and the "LastStationsUpdateCheck" tag. 🧐

**Comment by JazzfanRS** [comment]
Renamed Radiosure.xml to negate its presence in folder and deleted any station list in Stations folder. Same Error as above.
New station list placed in folder. Radiosure program creates a new XML upon opening of App.

XML present. No station lists. Same script error about line 100. Station list placed in folder. This is what happened every time I ever used the script. Only after using it the first time since it was released, I don't recall if I had installed it to APPDATA or to a secondary drive when this first occurred. It is installed on D: now.

**`Does your version of RS (2.2.1046 ??) use a configuration source other than the RadioSure.xml file? (the registry ??) `**
I use 1046 version exclusively. Not sure what you mean by alternate configuration. No, I only ever use the XML the program uses and never altered any registry settings.

I decided to reinstall from the original installer and choose default APPDATA folder. I did not choose portable (no registry adds). Same Results as D: installation. 
Which I noticed this: Using the genuine Radiosure installer (1046) and placing it in D:\Program Files(x86)\ does not show it as installed in Installed apps on my Windows 10, and I don't have any reason to keep it from being added to the registry,

I have noticed some new problems that are recent. Sometimes opening Radiosure hangs at initializing when trying to load the preset station, or any station if I select a different one. And eventually will say it cannot initialize. But works if I close it and re-open it again.

I'll likely do another OS re-install and start fresh. RadioSure is the only app I ever used that uses APPDATA as a default and so I will likely let it install there. I have the drives and an older PC that could handle a secondary drive and decided to try to keep the system drive separate.

The new script works flawlessly. Thank You.

**Comment by GHbasicuser** [comment]
Thanks again for the feedback.

When you say "XML present", does that mean the "LastStationsUpdateCheck" tag ? If so, then there's something I'm missing because for me there are only these 2 possibilities (xml file or tag missing), otherwise the error message wouldn't be on this line. 😐

I've just noticed that RS doesn't systematically include this tag in the XML file. 🧐 (I've adopted QMPlay2 a little too much. 😅) I think that's the explanation, especially if you haven't encountered any errors since the last script.

Please let me know if this problem occurs again. Thank you !
